import React from 'react';
import { Globe, Users, Clock, Users2, Layers, GraduationCap, Fish } from 'lucide-react';
export const GlobeIcon = () => <Globe className="h-5 w-5 text-blue-800" />;
export const UsersIcon = () => <Users className="h-5 w-5 text-blue-800" />;
export const ToolIcon = () => <div className="h-5 w-5 text-blue-800" />;
export const ClockIcon = () => <Clock className="h-5 w-5 text-blue-800" />;
export const DiversityIcon = () => <Users2 className="h-5 w-5 text-blue-800" />;
export const LayersIcon = () => <Layers className="h-5 w-5 text-blue-800" />;
export const GraduationCapIcon = () => <GraduationCap className="h-5 w-5 text-blue-800" />;
export const FishIcon = () => <Fish className="h-5 w-5 text-blue-500" />;